### ISSUE TITLE
Problems running train_SSTFormer.sh

### ISSUE THREAD

**Issue by AmamiyaKarin** [Event-AHU/SSTFormer#9]
Traceback (most recent call last):
  File "tools/train.py", line 136, in <module>
    main()
  File "tools/train.py", line 129, in main
    runner = Runner.from_cfg(cfg)
  File "……/anaconda3/envs/ECE/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "……/anaconda3/envs/ECE/lib/python3.8/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "……/anaconda3/envs/ECE/lib/python3.8/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "……/anaconda3/envs/ECE/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "……/anaconda3/envs/ECE/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "……/anaconda3/envs/ECE/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "……/mmaction2/mmaction/models/recognizers/base.py", line 116, in __init__
    self.backbone = MODELS.build(backbone)
  File "……/anaconda3/envs/ECE/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "……/anaconda3/envs/ECE/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "……/anaconda3/envs/ECE/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'SSTFormer is not in the mmaction::model registry. Please check whether the value of `SSTFormer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by WuZongzhen** [comment]
Thank you for your attention! SSTFormer has been added to the SSTFormer/mmaction/models/packages/__ init__. py file (from .SSTFormer import SSTFormer) , and I did not encounter the issue you mentioned.

**Comment by Hui-Sha** [comment]
Hello, has this problem been solved? I had the same problem
